## Context
The World Happiness Report is a landmark survey of the state of global happiness. The first report was published in 2012, the second in 2013, the third in 2015, and the fourth in the 2016 Update. The World Happiness 2017, which ranks 155 countries by their happiness levels, was released at the United Nations at an event celebrating International Day of Happiness on March 20th. The report continues to gain global recognition as governments, organizations and civil society increasingly use happiness indicators to inform their policy-making decisions. Leading experts across fields – economics, psychology, survey analysis, national statistics, health, public policy and more – describe how measurements of well-being can be used effectively to assess the progress of nations. The reports review the state of happiness in the world today and show how the new science of happiness explains personal and national variations in happiness.

## Content
The happiness scores and rankings use data from the Gallup World Poll. The scores are based on answers to the main life evaluation question asked in the poll. This question, known as the Cantril ladder, asks respondents to think of a ladder with the best possible life for them being a 10 and the worst possible life being a 0 and to rate their own current lives on that scale. The scores are from nationally representative samples for the years 2013-2016 and use the Gallup weights to make the estimates representative. The columns following the happiness score estimate the extent to which each of six factors – economic production, social support, life expectancy, freedom, absence of corruption, and generosity – contribute to making life evaluations higher in each country than they are in Dystopia, a hypothetical country that has values equal to the world’s lowest national averages for each of the six factors. They have no impact on the total score reported for each country, but they do explain why some countries rank higher than others.

## Inspiration
What countries or regions rank the highest in overall happiness and each of the six factors contributing to happiness? How did country ranks or scores change between the 2015 and 2016 as well as the 2016 and 2017 reports? Did any country experience a significant increase or decrease in happiness?

#### What is Dystopia?

Dystopia is an imaginary country that has the world’s least-happy people. The purpose in establishing Dystopia is to have a benchmark against which all countries can be favorably compared (no country performs more poorly than Dystopia) in terms of each of the six key variables, thus allowing each sub-bar to be of positive width. The lowest scores observed for the six key variables, therefore, characterize Dystopia. Since life would be very unpleasant in a country with the world’s lowest incomes, lowest life expectancy, lowest generosity, most corruption, least freedom and least social support, it is referred to as “Dystopia,” in contrast to Utopia.

#### What are the residuals?

The residuals, or unexplained components, differ for each country, reflecting the extent to which the six variables either over- or under-explain average 2014-2016 life evaluations. These residuals have an average value of approximately zero over the whole set of countries. Figure 2.2 shows the average residual for each country when the equation in Table 2.1 is applied to average 2014- 2016 data for the six variables in that country. We combine these residuals with the estimate for life evaluations in Dystopia so that the combined bar will always have positive values. As can be seen in Figure 2.2, although some life evaluation residuals are quite large, occasionally exceeding one point on the scale from 0 to 10, they are always much smaller than the calculated value in Dystopia, where the average life is rated at 1.85 on the 0 to 10 scale.

#### What do the columns succeeding the Happiness Score(like Family, Generosity, etc.) describe?

The following columns: GDP per Capita, Family, Life Expectancy, Freedom, Generosity, Trust Government Corruption describe the extent to which these factors contribute in evaluating the happiness in each country.
The Dystopia Residual metric actually is the Dystopia Happiness Score(1.85) + the Residual value or the unexplained value for each country as stated in the previous answer.

If you add all these factors up, you get the happiness score so it might be un-reliable to model them to predict Happiness Scores.


### Acknowledgements
I did not create this data, only sourced it. The credit goes to the original Authors:

Editors: John Helliwell, Richard Layard, Jeffrey D. Sachs, and Jan Emmanuel De Neve, Co-Editors; Lara Aknin, Haifang Huang and Shun Wang, Associate Editors; and Sharon Paculor, Production Editor

### Citation:
Helliwell, John F., Richard Layard, Jeffrey Sachs, and Jan-Emmanuel De Neve, eds. 2020. World Happiness Report 2020. New York: Sustainable Development Solutions Network

In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn

### Let's look at the data

In [49]:
df_2015 = pd.read_csv('data/2015.csv')
df_2016 = pd.read_csv('data/2016.csv')
df_2017 = pd.read_csv('data/2017.csv')
df_2018 = pd.read_csv('data/2018.csv')
df_2019 = pd.read_csv('data/2019.csv')
df_2020 = pd.read_csv('data/2020.csv')
df_2021 = pd.read_csv('data/2021.csv')

In [50]:
df_2021 = df_2021.drop(['Logged GDP per capita', 'Social support','Healthy life expectancy','Freedom to make life choices','Generosity','Perceptions of corruption','Ladder score in Dystopia'], axis=1)

In [51]:
df_2020 = df_2020.drop(['Logged GDP per capita', 'Social support','Healthy life expectancy','Freedom to make life choices','Generosity','Perceptions of corruption','Ladder score in Dystopia'], axis=1)

In [52]:
print('2015', df_2015.shape)
print('2016', df_2016.shape)
print('2017', df_2017.shape)
print('2018', df_2018.shape)
print('2019', df_2019.shape)
print('2020', df_2020.shape)
print('2021', df_2021.shape)

2015 (158, 12)
2016 (157, 13)
2017 (155, 12)
2018 (156, 9)
2019 (156, 9)
2020 (153, 13)
2021 (149, 13)

In [53]:
df_2020

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Central African Republic,Sub-Saharan Africa,3.4759,0.115183,3.701658,3.250141,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198
149,Rwanda,Sub-Saharan Africa,3.3123,0.052425,3.415053,3.209547,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445
150,Zimbabwe,Sub-Saharan Africa,3.2992,0.058674,3.414202,3.184198,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031
151,South Sudan,Sub-Saharan Africa,2.8166,0.107610,3.027516,2.605684,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751
152,Afghanistan,South Asia,2.5669,0.031311,2.628270,2.505530,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236

In [54]:
def rename_columns(df):
    
    columns_lst = list(df.columns)
    for name in columns_lst:
        if 'Rank' in name or 'rank' in name:
            df = df.rename(columns = {name: 'Happiness Rank'})
        elif 'Standard' in name or 'standard' in name:
            df = df.rename(columns = {name: 'Standard Error'})                        
        elif 'Score' in name or 'score' in name:
            df = df.rename(columns = {name: 'Happiness Score'})
        elif 'high' in name:
            df = df.rename(columns = {name: 'Upper Confidence Interval'})   
        elif 'low' in name:
            df = df.rename(columns = {name: 'Lower Confidence Interval'}) 
        elif 'GDP' in name:
            df = df.rename(columns = {name: 'Economy (GDP per Capita)'})
        elif 'Family' in name:
            df = df.rename(columns = {name: 'Family'})  
        elif 'Health' in name:
            df = df.rename(columns = {name: 'Health (Life Expectancy)'})                        
        elif 'Freedom' in name:
            df = df.rename(columns = {name: 'Freedom'})            
        elif 'Generosity' in name:
            df = df.rename(columns = {name: 'Generosity'})    
        elif 'Government' in name or 'corruption' in name:
            df = df.rename(columns = {name: 'Trust (Government Corruption)'})                        
        elif 'Dystopia' in name:
            df = df.rename(columns = {name: 'Dystopia Residual'})                        
        elif 'Country' in name:
            df = df.rename(columns = {name: 'Country'})            
        elif 'Region' in name:
            df = df.rename(columns = {name: 'Region'})     
        elif 'Social' in name:
            df = df.rename(columns = {name: 'Social support'})

    return df

In [55]:
df_2015 = rename_columns(df_2015)
df_2016 = rename_columns(df_2016)
df_2017 = rename_columns(df_2017)
df_2018 = rename_columns(df_2018)
df_2019 = rename_columns(df_2019)
df_2020 = rename_columns(df_2020)
df_2021 = rename_columns(df_2021)

In [56]:
print('2015', df_2015.shape)
print('2016', df_2016.shape)
print('2017', df_2017.shape)
print('2018', df_2018.shape)
print('2019', df_2019.shape)
print('2020', df_2020.shape)
print('2021', df_2021.shape)

2015 (158, 12)
2016 (157, 13)
2017 (155, 12)
2018 (156, 9)
2019 (156, 9)
2020 (153, 13)
2021 (149, 13)

In [57]:
df_2020

,Country,Region,Happiness Score,Standard Error,upperwhisker,Lower Confidence Interval,Economy (GDP per Capita),Social support,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Central African Republic,Sub-Saharan Africa,3.4759,0.115183,3.701658,3.250141,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198
149,Rwanda,Sub-Saharan Africa,3.3123,0.052425,3.415053,3.209547,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445
150,Zimbabwe,Sub-Saharan Africa,3.2992,0.058674,3.414202,3.184198,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031
151,South Sudan,Sub-Saharan Africa,2.8166,0.107610,3.027516,2.605684,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751
152,Afghanistan,South Asia,2.5669,0.031311,2.628270,2.505530,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236

In [58]:
def country_or_region(df):
    regions = ['Western Europe',
 'North America',
 'Australia and New Zealand',
 'Middle East and Northern Africa',
 'Latin America and Caribbean',
 'Southeastern Asia',
 'Central and Eastern Europe',
 'Eastern Asia',
 'Sub-Saharan Africa',
 'Southern Asia']
    for i in range(df.shape[0]):
        if df.loc[i, 'Country'] in regions:
            df.drop([i])
            
    return df

In [59]:
df_2015 = country_or_region(df_2015)
df_2016 = country_or_region(df_2016)
df_2017 = country_or_region(df_2017)
df_2018 = country_or_region(df_2018)
df_2019 = country_or_region(df_2019)
df_2020 = country_or_region(df_2020)
df_2021 = country_or_region(df_2021)

In [60]:
print('2015', df_2015.shape)
print('2016', df_2016.shape)
print('2017', df_2017.shape)
print('2018', df_2018.shape)
print('2019', df_2019.shape)
print('2020', df_2020.shape)
print('2021', df_2021.shape)

2015 (158, 12)
2016 (157, 13)
2017 (155, 12)
2018 (156, 9)
2019 (156, 9)
2020 (153, 13)
2021 (149, 13)

In [65]:
def add_rank(df):
    if 'Happiness Rank' not in df:

        df.sort_values(by=['Happiness Score'])
        df['Happiness Rank'] = list(range(1, df.shape[0] + 1))

    return df

In [66]:
df_2015 = add_rank(df_2015)
df_2016 = add_rank(df_2016)
df_2017 = add_rank(df_2017)
df_2018 = add_rank(df_2018)
df_2019 = add_rank(df_2019)
df_2020 = add_rank(df_2020)
df_2021 = add_rank(df_2021)

In [67]:
print('2015', df_2015.shape)
print('2016', df_2016.shape)
print('2017', df_2017.shape)
print('2018', df_2018.shape)
print('2019', df_2019.shape)
print('2020', df_2020.shape)
print('2021', df_2021.shape)

2015 (158, 12)
2016 (157, 13)
2017 (155, 12)
2018 (156, 9)
2019 (156, 9)
2020 (153, 14)
2021 (149, 14)

In [9]:
def add_region(df_region, df_no_region):
    """
    Function adds region to data frame 
    """
    if 'Region' not in df_region and 'Region' not in df_no_region:
        print("Region column does not exist in neither of the data frames")
        print()
        print("Please select a data frame that contains Region column")
        
    if 'Region' not in df_region and 'Region' in df_no_region:
        temp_df = df_region.copy()
        df_region = df_no_region.copy()
        df_no_region = temp_df.copy()
        
    if 'Region' not in df_no_region:
        df_no_region['Region'] = None
        for i in range(df_region.shape[0]):
            for k in range(df_no_region.shape[0]):        
                if df_no_region.loc[k, 'Country'] == df_region.loc[i, 'Country']:
                    df_no_region.loc[k, 'Region'] = df_region.loc[i, 'Region']

    return df_no_region

In [68]:
df_2015 = add_region(df_2015, df_2015)
df_2016 = add_region(df_2016, df_2015)
df_2017 = add_region(df_2017, df_2015)
df_2018 = add_region(df_2018, df_2015)
df_2019 = add_region(df_2019, df_2015)
df_2020 = add_region(df_2020, df_2015)
df_2021 = add_region(df_2021, df_2015)

In [69]:
print('2015', df_2015.shape)
print('2016', df_2016.shape)
print('2017', df_2017.shape)
print('2018', df_2018.shape)
print('2019', df_2019.shape)
print('2020', df_2020.shape)
print('2021', df_2021.shape)

2015 (158, 12)
2016 (158, 12)
2017 (155, 13)
2018 (156, 10)
2019 (156, 10)
2020 (158, 12)
2021 (158, 12)

In [71]:
def add_SE(df):
    """
    Function adds Standard Error to Data Frame with 95% Confidence Interval 
    using Lower Confidence Interval
    Rearranges the colunms 
    """
    if 'Lower Confidence Interval' in df and 'Happiness Score' in df:
        df['Standard Error'] = (df['Happiness Score'] - df['Lower Confidence Interval']) / 1.96
    
    
    return df

In [72]:
df_2015 = add_SE(df_2015)
df_2016 = add_SE(df_2016)
df_2017 = add_SE(df_2017)
df_2018 = add_SE(df_2018)
df_2019 = add_SE(df_2019)
df_2020 = add_SE(df_2020)
df_2021 = add_SE(df_2021)

In [73]:
print('2015', df_2015.shape)
print('2016', df_2016.shape)
print('2017', df_2017.shape)
print('2018', df_2018.shape)
print('2019', df_2019.shape)
print('2020', df_2020.shape)
print('2021', df_2021.shape)

2015 (158, 12)
2016 (158, 12)
2017 (155, 14)
2018 (156, 10)
2019 (156, 10)
2020 (158, 12)
2021 (158, 12)

In [74]:
df_2017

,Country,Happiness Rank,Happiness Score,Upper Confidence Interval,Lower Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual,Region,Standard Error
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027,Western Europe,0.029308
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707,Western Europe,0.030474
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715,Western Europe,0.060220
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716,Western Europe,0.034578
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182,Western Europe,0.029868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061,Sub-Saharan Africa,0.036750
151,Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574,Middle East and Northern Africa,0.102892
152,Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130,Sub-Saharan Africa,0.057362
153,Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024,Sub-Saharan Africa,0.086577
154,Central African Republic,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005,Sub-Saharan Africa,0.087696

In [75]:
def add_CI(df):
    
    """
    Function adds Confidence Interval using 
    mean Happiness Score and Standard Error assuming 95% CI
    """
    if 'Standard Error' in df and 'Happiness Score' in df:

        df['Lower Confidence Interval'] = df['Happiness Score'] - 1.96 * df['Standard Error']
        df['Upper Confidence Interval'] = df['Happiness Score'] + 1.96 * df['Standard Error']


    return df

In [76]:
df_2015 = add_CI(df_2015)
df_2016 = add_CI(df_2016)
df_2017 = add_CI(df_2017)
df_2018 = add_CI(df_2018)
df_2019 = add_CI(df_2019)
df_2020 = add_CI(df_2020)
df_2021 = add_CI(df_2021)

In [77]:
print('2015', df_2015.shape)
print('2016', df_2016.shape)
print('2017', df_2017.shape)
print('2018', df_2018.shape)
print('2019', df_2019.shape)
print('2020', df_2020.shape)
print('2021', df_2021.shape)

2015 (158, 14)
2016 (158, 14)
2017 (155, 14)
2018 (156, 10)
2019 (156, 10)
2020 (158, 14)
2021 (158, 14)

In [12]:
def reorder(df):
    df = df.reindex(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
   'Standard Error', 'Lower Confidence Interval', 'Upper Confidence Interval', 'Economy (GDP per Capita)', 'Family',
    'Social Support', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
   'Generosity', 'Dystopia Residual'], axis = 1)
    df.sort_values(by=['Happiness Rank'])

    return df

In [ ]:
df_2015 = reorder(df_2015)
df_2016 = reorder(df_2016)
df_2017 = reorder(df_2017)
df_2018 = reorder(df_2018)
df_2019 = reorder(df_2019)
df_2020 = reorder(df_2020)
df_2021 = reorder(df_2021)

In [13]:
def add_year(df, year):
    df['year'] = year
    
    return df

In [121]:
df_2019

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...
151,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,156,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091

In [122]:
df_2018

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...
151,152,Yemen,3.355,0.442,1.073,0.343,0.244,0.083,0.064
152,153,Tanzania,3.303,0.455,0.991,0.381,0.481,0.270,0.097
153,154,South Sudan,3.254,0.337,0.608,0.177,0.112,0.224,0.106
154,155,Central African Republic,3.083,0.024,0.000,0.010,0.305,0.218,0.038
155,156,Burundi,2.905,0.091,0.627,0.145,0.065,0.149,0.076

In [114]:
df_2017

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182
...,...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
151,Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
152,Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
153,Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
154,Central African Republic,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005

#### Happiness Rank
Rank of the country based on the Happiness Score.

#### Happiness Score
A metric measured in 2015 by asking the sampled people the question: "How would you rate your happiness on a scale of 0 to 10 where 10 is the happiest."

#### Standard Error
The standard error of the happiness score.

#### Economy (GDP per Capita)
The extent to which GDP contributes to the calculation of the Happiness Score.

#### Family
The extent to which Family contributes to the calculation of the Happiness Score

#### Health (Life Expectancy)
The extent to which Life expectancy contributed to the calculation of the Happiness Score

#### Freedom
The extent to which Freedom contributed to the calculation of the Happiness Score.

#### Trust (Government Corruption)
The extent to which Perception of Corruption contributes to Happiness Score.

#### Generosity
The extent to which Generosity contributed to the calculation of the Happiness Score.

#### Dystopia Residual
The extent to which Dystopia Residual contributed to the calculation of the Happiness Score.

In [7]:
df.describe()

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,79.493671,5.375734,0.047885,0.846137,0.991046,0.630259,0.428615,0.143422,0.237296,2.098977
std,45.754363,1.145010,0.017146,0.403121,0.272369,0.247078,0.150693,0.120034,0.126685,0.553550
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580
25%,40.250000,4.526000,0.037268,0.545808,0.856823,0.439185,0.328330,0.061675,0.150553,1.759410
50%,79.500000,5.232500,0.043940,0.910245,1.029510,0.696705,0.435515,0.107220,0.216130,2.095415
75%,118.750000,6.243750,0.052300,1.158448,1.214405,0.811013,0.549092,0.180255,0.309883,2.462415
max,158.000000,7.587000,0.136930,1.690420,1.402230,1.025250,0.669730,0.551910,0.795880,3.602140

In [6]:
df.shape

(158, 12)

### 1. Was there a change over the years in average happiness score around the world?
### 2. Was the change significant?
### 3. What were the countries that contributed to the change?
### 4. Why was there a change in the countries?